### ISSUE TITLE
backtrader/store.py Undefined variable 'self' 

### ISSUE THREAD

**Issue by OpenTrading** [backtrader/backtrader#361]
Pylint piacked this up at line 61:

Module backtrader.store
E: 61,24: Undefined variable 'self' (undefined-variable)

**Comment by OpenTrading** [comment]
Why was this closed - has it been fixed already?
In python, undefined variables is a considered a bug - you should run a linter on your code

If you close issues that are bugs without comment we'll understand that you are not supporting the software and don't want us to use it.

**Comment by backtrader** [comment]
Who is "we"? Are you an entity like the Borg collective?

Which exact problem do you have?

It is very nice and kind fror you to consider things. but who is "we" to consider the software unsupported?

Do you pay for support?

It is really not polite to be a Serial-Bug Opener with no description of what the problem may be and then complain and make statements about the support of the software.

If "we" wants to make bug reports, consider them making real bug reports.
